# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Studio Universus
email: contato@studiouniversus.com.br
description: Studio de sobrancelhas e esmalteria com técnicas exclusivas.
  Competência, receptividade e segurança com sua saúde é nossa obrigação.
  Nós iremos além para lhe proporcionar uma ótima experiência a cada cuidado.
about: Nós temos o que você precisa!
about_description: Sua satisfação é o nosso maior objetivo.
  Cuidados com sobrancelhas e unhas a cada se tornam mais... (Criar um pequeno texto)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://studiouniversus.com.br" # the base hostname & protocol for your site
facebook_username: jekyllrb
instagram_username:  jekyll

# Build settings
markdown: kramdown

#sass:
  # loading path from site root
  # default to _sass
  #sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  #style: compressed

exclude: [gulpfile.js, package.json, node_modules, bower.json, bower_components]